#!/usr/bin/env python
from sklearn.metrics import accuracy_score
def score(y, probas, thresholds):
	scores = []
	for thresh in thresholds:
		newprobas = []
		for p in probas:
			if p>thresh:
				newprobas.extend(1)
			else:
				newprobas.extend(0)

	scores.extend(accuracy_score(y, newprobas))


score([1, 0, 1, 0], [.6, .4, .6, .4], [.3, .5, .7])